import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'ja';

type Translations = Record<string, Record<string, string>>;

const translations: Translations = {
  en: {
    'home.label': 'A community for app ideas',
    'home.hero': 'Grow app ideas together.',
    'home.subhero': 'App Gardenium is a place to plant your "wish it existed" ideas, share them with the community, and grow them into real applications together.',
    'home.exploreBtn': 'Explore Ideas',
    'home.postBtn': 'Plant an Idea',
    'home.howItWorks': 'The Growth Journey',
    'home.step1Title': 'Plant a Seed',
    'home.step1Desc': 'Just share what "you wish existed". No technical skills needed—simply describe a problem or a wish.',
    'home.step2Title': 'Nourish Regularly',
    'home.step2Desc': 'Get feedback and support from the community. Ideas gradually take shape and evolve into something truly needed.',
    'home.step3Title': 'Bear Fruit',
    'home.step3Desc': 'Indie developers build the idea and meet testers. App Gardenium supports you all the way to release.',
    'home.sproutingTitle': 'Sprouting Now',
    'home.sproutingDesc': 'Ideas gathering momentum in the community.',
    'home.viewAll': 'View all',
    'home.devTitle': 'For Developers',
    'home.devDesc': 'Tired of building apps nobody wants? Discover validated problems, connect with passionate potential users, or bring your WIP "sapling" apps for community feedback.',
    'home.devBtn': 'Find ideas to build',
    'home.testerTitle': 'Become a Tester',
    'home.testerDesc': 'Get early access to tools that solve your specific problems. Your feedback directly shapes the final product.',
    'home.testerBtn': 'Join as Tester',
    'home.loadingIdeas': 'Loading ideas...',
    'home.shippedEmptyDesc': 'Ideas are quietly sprouting in the Greenhouse space. Soon, this section will be filled with apps that blossomed from community seeds.',
    'home.shippedEmptyBtn': 'Find a Seed to Build',
    'stage.seed': 'Seed (Idea)',
    'stage.sprout': 'Sprout (Prototype)',
    'stage.growing': 'Nourishing',
    'stage.testing': 'Testing',
    'stage.polishing': 'Polishing',
    'stage.launching': 'Coming Soon',
    'stage.released': 'Bore Fruit',
    'stage.archived': 'Archived',
    'nav.explore': 'Explore',
    'nav.home': 'Home',
    'nav.submit': 'Plant Idea',
    'nav.login': 'Log in',
    'nav.profile': 'Profile',
    'nav.pricing': 'Pricing',
    'nav.salon': 'Greenhouse',
    'login.titlePrefix': 'Welcome to',
    'login.subtitle': 'Join a community of builders and dreamers. Let\'s grow ideas together.',
    'login.signingIn': 'Signing in...',
    'login.continueGoogle': 'Continue with Google',
    'login.termsPrefix': 'By continuing, you agree to our ',
    'login.termsAnd': ' and ',
    'login.termsSuffix': '.',
    'login.error.popupBlocked': 'The sign-in popup was blocked. We\'ll try a full-page Google sign-in instead.',
    'login.error.network': 'Network error during sign-in. Please check your connection and try again.',
    'login.error.unauthorizedDomain': 'This domain is not enabled for Google sign-in yet. Please check Firebase Authentication settings.',
    'login.error.generic': 'Could not sign in right now. Please try again.',
    'status.public': 'Public',
    'status.private': 'Private',
    'status.pending': 'Processing',
    'status.paid': 'Paid',
    'status.fulfilled': 'Delivered',
    'status.failed': 'Failed',
    'commerce.legalTitle': 'Commercial Disclosure',
    'commerce.back': 'Back to Shop',
    'common.you': 'You',
    'common.anonymous': 'Anonymous',
    'common.sproutThinker': 'Sprout Thinker',
    'common.sproutBuilder': 'Sprout Builder',
    'profile.editProfile': 'Edit Profile',
    'profile.displayName': 'Display Name',
    'profile.bio': 'Bio',
    'profile.bioPlaceholder': 'Tell the community about yourself...',
    'profile.skills': 'Skills',
    'profile.skillsPlaceholder': 'e.g. React, UX Design, Marketing',
    'profile.twitter': 'Twitter',
    'profile.github': 'GitHub',
    'profile.website': 'Website',
    'profile.cancel': 'Cancel',
    'profile.save': 'Save',
    'profile.growingSince': 'Growing app ideas since',
    'profile.recently': 'recently',
    'profile.ideas': 'Ideas',
    'profile.supported': 'Supported',
    'profile.comments': 'Comments',
    'profile.testsJoined': 'Tests Joined',
    'profile.plantedIdeas': 'Planted Ideas',
    'profile.supportedIdeas': 'Supported Ideas',
    'profile.builtApps': 'Built Apps',
    'profile.addApp': 'Add App',
    'profile.recruitTesters': 'Recruit Testers',
    'profile.addAppTitle': 'Add Shipped App',
    'profile.appNameLabel': 'App Name',
    'profile.appDescLabel': 'Short Description',
    'profile.appUrlLabel': 'App URL',
    'profile.addAppSubmit': 'Save App',
    'profile.nothingBuilt': 'No apps built yet',
    'profile.nothingBuiltDesc': 'Find hints from promising ideas and turn them into your first app.',
    'profile.noIdeas': 'No seeds planted yet',
    'profile.noIdeasDesc': 'Why not share your own "I wish this existed" idea?',
    'profile.noSupported': 'No supported ideas yet',
    'profile.noSupportedDesc': 'Start by giving a gentle reaction to someone else\'s seed.',
    'profile.startPlanted': 'Plant your first idea',
    'profile.startExplore': 'Explore ideas to build',
    'profile.startSalon': 'Visit the Greenhouse',
    'profile.logout': 'Log out',
    'profile.visitApp': 'Visit App',
    'profile.avatarModerationError': 'Inappropriate image detected. Please choose a different avatar.',
    'commerce.aiTickets': 'Growth Guide (AI Features)',
    'commerce.balance': 'Remaining',
    'membership.topup.title': 'Top-up Menu',
    'membership.topup.desc': 'Even without a monthly plan, you can add only the push you need.',
    'membership.topup.boost.title': 'Visibility Boost (7 days)',
    'membership.topup.boost.desc': 'Give your idea page another chance to be seen.',
    'membership.topup.boost.status': 'This month: {count}',
    'membership.topup.boost.button': '{price} Purchase',
    'membership.topup.report.title': 'AI Deep Review',
    'membership.topup.report.desc': 'Get one deeper AI pass for positioning and next steps.',
    'membership.topup.report.status': 'Remaining: {count}',
    'membership.topup.report.button': '{price} Purchase',
    'membership.topup.tester.title': 'Tester Recruitment Boost',
    'membership.topup.tester.desc': 'Strengthen one tester call and make it easier to gather early users.',
    'membership.topup.tester.status': 'Remaining: {count}',
    'membership.topup.tester.button': '{price} Purchase',
    'commerce.balanceUnit': 'uses',
    'commerce.ticketDesc': 'Organize ideas and summarize feedback. Let AI assist your gardening process.',
    'commerce.instantFulfillment': 'Instant Delivery',
    'commerce.footerTicketDesc': 'Available immediately for AI features after purchase.',
    'commerce.confirmPurchase': 'Confirm Purchase',
    'commerce.proceedToPurchase': 'Proceed to Purchase',
    'commerce.purchaseAmount': 'Purchase Amount',
    'commerce.deliveryTiming': 'Delivery',
    'report.title': 'AI Analysis Report',
    'report.generatedBy': 'Generated AI Analysis',
    'report.summaryLabel': 'Reaction Summary',
    'report.commonRequestsLabel': 'Common Requests',
    'report.concernsLabel': 'Key Concerns',
    'report.nextActionsLabel': 'Recommended Next Actions',
    'report.analyzedAt': 'Analyzed at',
    'report.onlyLatestDesc': 'Analyzing only the latest reactions',

    // Membership / Billing Management
    'membership.title': 'Membership & Plan',
    'membership.currentPlan': 'Current Plan',
    'membership.status': 'Membership Status',
    'membership.status.active': 'Active',
    'membership.status.pending': 'Processing Status',
    'membership.status.canceled': 'Canceled',
    'membership.status.past_due': 'Payment Required',
    'membership.status.inactive': 'No Active Plan',
    'membership.status.free': 'Free User',

    // Membership State Details
    'membership.state.active.label': 'Active',
    'membership.state.active.desc': 'Your membership benefits are currently available.',
    'membership.state.pending.label': 'Pending activation',
    'membership.state.pending.desc': 'Your payment is complete, but membership benefits may take a moment to appear.',
    'membership.state.renewing.label': 'Renewing',
    'membership.state.renewing.desc': 'Your membership is active and set to renew automatically.',
    'membership.state.payment_issue.label': 'Payment action needed',
    'membership.state.payment_issue.desc': 'There may be an issue with renewal. Please review your payment method.',
    'membership.state.cancel_scheduled.label': 'Scheduled to cancel',
    'membership.state.cancel_scheduled.desc': 'Your membership will remain active until the end of the current billing period.',
    'membership.state.canceled.label': 'Canceled',
    'membership.state.canceled.desc': 'Your paid membership has ended. You can continue using App Gardenium on the free plan.',
    'membership.state.expired.label': 'Back on Free',
    'membership.state.expired.desc': 'Your paid benefits have ended, but you can still use App Gardenium for free, including the beta Greenhouse and the daily AI helper quota.',

    'membership.manage': 'Manage Plan',
    'membership.payment': 'Payment Method',
    'membership.cancel': 'Cancel Membership',
    'membership.perks': 'Your Current Perks',
    'membership.greenhouse': 'Visit the Greenhouse space',
    'membership.post': 'Share Progress Now',
    'membership.reflectNotice': 'Payment status may take a moment to reflect.',
    'membership.upgradePro': 'Step up to Pro',
    'membership.upgradeSupporter': 'Become a Supporter',
    'membership.billingHistory': 'Billing History',
    'membership.changePayment': 'Update Payment Method',
    'membership.portalDesc': 'Manage your subscription, billing history, and payment methods via Stripe Secure Portal.',
    'membership.openPortal': 'Open Customer Portal',
    'membership.startedAt': 'Member since',
    'membership.nextStep': 'Next Step',
    'membership.reloadStatus': 'Reload Status',
    'membership.keepFree': 'Keep using for free',
    'membership.checkRenewal': 'Check Renewal Date',

    'billing.currentPlan': 'Current Plan',
    'billing.startThisPlan': 'Start this plan',
    'billing.managePlan': 'Manage Plan',
    'billing.upgrade': 'Upgrade to Pro',
    'billing.confirm.header': 'Please confirm your order before proceeding',
    'billing.confirmJoin': 'Join {plan}',
    'billing.confirmDesc': 'You are joining the {plan} plan. Your benefits will be unlocked immediately after payment.',
    'billing.billingCycle': 'Billed monthly',
    'billing.proceedToCheckout': 'Confirm and proceed to checkout',
    'billing.termsAgreement': 'By proceeding, you agree to our terms and conditions.',
    'billing.viewLegal': 'View Legal Commerce Disclosure',
    'billing.confirm.legalNote': 'Please review the terms before purchase. For cancellations and refunds, see the Legal Disclosure page.',
    'billing.processing': 'Processing...',
    'billing.successTitle': 'Thank you for joining!',
    'billing.successSubSupporter': 'Welcome to Supporter. You now have a steadier place to keep growing your idea.',
    'billing.successSubPro': 'Welcome to Pro. Let’s move your project closer to launch from here.',
    'billing.reflectingNotice': 'Membership benefits may take a moment to appear after payment.',
    'billing.unlockedFeatures': 'What you just unlocked',
    'billing.startHere': 'Start here',
    'billing.startHerePro': 'Take your first step',
    
    // Plan Confirmation Details - Supporter
    'plan.supporter.confirmTitle': 'Start Supporter',
    'plan.supporter.confirmSub': 'A seat for nurturing steadily. Post more ideas, run the Growth Agent up to 10 times a month, and shape tester calls and share copy.',
    'plan.supporter.price': '¥300 / month (tax included)',
    'plan.supporter.cycle': 'Billed monthly (auto-renewal)',
    'plan.supporter.note': 'It\'s okay to start just by reading.',
    'plan.supporter.f1': 'Supporter badge reflected on your profile',
    'plan.supporter.f2': 'Post more ideas and keep dev logs going',
    'plan.supporter.f3': 'Growth Agent up to 10 times / month',
    'plan.supporter.f4': 'Tester Strategy and Share Boost drafts',
    'plan.supporter.f5': 'Greenhouse access and a visible Supporter presence',

    // Plan Confirmation Details - Pro
    'plan.pro.confirmTitle': 'Start Pro',
    'plan.pro.confirmSub': 'A seat for getting ready to launch. Organize next steps, review store submission risks, and prepare share and SEO copy.',
    'plan.pro.price': '¥980 / month (tax included)',
    'plan.pro.cycle': 'Billed monthly (auto-renewal)',
    'plan.pro.note': 'For builders who want to move from growth into launch preparation.',
    'plan.pro.f1': 'Pro badge reflected on your profile',
    'plan.pro.f2': 'Growth Agent up to 50 times / month',
    'plan.pro.f3': 'Store Review Readiness',
    'plan.pro.f4': 'Share Boost variants and SEO / OGP copy',
    'plan.pro.f5': 'Tester recruitment boost and stronger visibility',
    'plan.pro.f6': 'One monthly priority boost',
    
    // Steps - Supporter
    'billing.step.supporter1.title': 'Plant a few more ideas',
    'billing.step.supporter1.desc': 'Use your extra room to keep exploring instead of compressing everything into one draft.',
    'billing.step.supporter2.title': 'Run Growth Agent',
    'billing.step.supporter2.desc': 'Turn one idea into clearer tester strategy and share-ready direction.',
    'billing.step.supporter3.title': 'Keep the rhythm going',
    'billing.step.supporter3.desc': 'Use logs, drafts, and the Greenhouse to keep your project warm.',
    
    // Steps - Pro
    'billing.step.pro1.title': 'Run launch-focused reviews',
    'billing.step.pro1.desc': 'Use Growth Agent, Store Review Readiness, and Share Boost on one idea.',
    'billing.step.pro2.title': 'Tighten the public story',
    'billing.step.pro2.desc': 'Prepare tester call copy, share variants, and SEO / OGP text.',
    'billing.step.pro3.title': 'Move toward release',
    'billing.step.pro3.desc': 'Use the monthly boost and next-step structure to get closer to launch.',

    // Actions
    'billing.action.viewGreenhouse': 'Visit the Greenhouse space',
    'billing.action.postProgress': 'Share Progress Now',
    'billing.action.goHome': 'Back to Home',
    'billing.action.viewProfile': 'Check My Profile',

    // Cancel
    'billing.cancelTitle': 'Landed back gently',
    'billing.cancelDesc': 'App Gardenium is always here for you to use at your own pace for free. Whenever you feel ready, the member seats will be waiting.',
    'billing.backToPricing': 'Back to Plans',
    'pricing.badge': 'Tailored to your development pace',
    'pricing.heroTitle': 'From seed idea to launch prep.',
    'pricing.heroSub': 'Start for free, then add the support you need for growth, tester recruitment, store review readiness, and share-ready copy.',
    'pricing.plan.freeShort': 'Place a seed.',
    'pricing.plan.freeTitle': 'Start with a Seed',
    'pricing.plan.freeDesc': 'Put your idea out there, make a public page, and see if it starts to resonate.',
    'pricing.plan.freeNote': 'A gentle starting point for testing the soil.',
    'pricing.plan.supporterShort': 'Keep nurturing.',
    'pricing.plan.supporterTitle': 'Keep Nurturing',
    'pricing.plan.supporterDesc': 'For solo builders who want to keep going with clearer drafts, tester strategy, and share copy.',
    'pricing.plan.supporterNote': 'A small monthly push to keep your idea alive.',
    'pricing.plan.supporterTag': 'Steady growth',
    'pricing.plan.proShort': 'Get ready to launch.',
    'pricing.plan.proTitle': 'Launch-Ready Pro',
    'pricing.plan.proDesc': 'For builders who want store review risk checks, stronger share output, and a clearer path toward release.',
    'pricing.plan.proNote': 'When you want help turning momentum into launch readiness.',
    'pricing.plan.proTag': 'Launch and review prep',
    'pricing.whoFree': 'People who want to place an idea quickly and see whether anyone responds.',
    'pricing.whoSupporter': 'People who want to nurture one idea steadily with AI help and better sharing.',
    'pricing.whoPro': 'People who want to move from growth into recruitment, review prep, and launch.',
    'pricing.salonTitle': 'Member Greenhouse space',
    'pricing.salonDesc': 'A semi-private sanctuary where you can share small wins and honest doubts. Don\'t develop alone.',
    'pricing.salonSupporterSub': 'Start by reading.',
    'pricing.salonSupporterDesc': 'During beta, all logged-in users can join the Greenhouse. Supporter helps keep it open and gives you a clearer presence.',
    'pricing.salonProSub': 'Share progress with more reach.',
    'pricing.salonProDesc': 'During beta, posting is open to logged-in users. Pro adds stronger visibility, boost-ready tools, and room to move faster.',
    'pricing.boostTitle': 'Shine a light when you need it',
    'pricing.boostDesc': 'Give your WIP app a chance to be rediscovered. Boosts are for growth, not just attention.',
    'pricing.boostSupporterSub': 'Supporter: lighter momentum',
    'pricing.boostSupporterDesc': 'Use Supporter when you want steady Growth Agent help without jumping all the way to launch prep.',
    'pricing.boostProSub': 'Pro: launch-facing momentum',
    'pricing.boostProDesc': 'Pro adds store review checks, stronger share output, and one monthly priority boost.',
    'pricing.ctaTitle': 'It all starts with a seed.',
    'pricing.ctaSubtitle': 'Why not start today?',
    'pricing.ctaDesc': 'Plant an idea and wait for reactions',
    'pricing.ctaBtn': 'Start for Free',
    'pricing.initialCost': 'Initial cost ¥0',
    'pricing.cancelAnytime': 'Cancel anytime',
    'pricing.footerNote': 'Supporting Lone Creators and Tiny Ideas.',
    'pricing.freeLabel': 'First steps',
    'pricing.supporterLabel': 'Preparing the soil',
    'pricing.proLabel': 'Taking the next step',
    'pricing.startFree': 'Start Free',
    'pricing.becomeSupporter': 'Become a Supporter',
    'pricing.startPro': 'Start with Pro',
    'pricing.whoIsItFor': 'Who is this for?',
    'pricing.comparison': 'Plan Comparison',
    'pricing.oneTime': 'One-time Top-ups',
    'pricing.oneTimeDesc': 'Single purchases for when you need one more push. Store Review Readiness is included in Pro.',
    'pricing.faqTitle': 'Frequently Asked Questions',
    'salon.title': 'Greenhouse Space',
    'salon.subtitle': 'A safe place to put your works in progress.',
    'salon.desc': 'Drop your tiny updates, casual doubts, and half-baked ideas here. You don\'t need to do it all alone.',
    'salon.supporterBadge': 'Supporter',
    'salon.proBadge': 'Pro',
    'salon.postIdea': 'What did you grow today?',
    'salon.postIdeaHint': 'It\'s okay if it\'s not finished. Even a single screenshot or a question is welcome.',
    'salon.postBtn': 'Leave a trace',
    'salon.postConsultBtn': 'Ask a light question',
    'salon.upgradePromptTitle': 'Want to share your progress?',
    'salon.upgradePromptDesc': 'During beta, every logged-in maker can post, comment, and react here. Keep the atmosphere gentle, unfinished, and easy to join.',
    'salon.upgradeBtn': 'Learn about Pro',
    'salon.themeTitle': 'Weekly Prompt',
    'salon.themeDesc': 'This week, we are looking for...',
    'salon.themeTopic': 'What does your first screen look like?',
    'salon.themeCurrent': 'Theme: Conveying value in 10 seconds.',
    'salon.wipTitle': "This Week's Sprouts",
    'salon.wipDesc': 'Updates and progress from the community.',
    'salon.wipEmpty': 'No sprouts have grown yet this week.',
    'salon.consultTitle': 'Seedbed for Thoughts',
    'salon.consultDesc': 'Members are asking for casual feedback and opinions.',
    'salon.boostTitle': 'Bathed in Sunlight',
    'salon.boostDesc': 'WIPs making steady progress that deserve a little more attention.',
    'salon.guideTitle': 'How to spend time here',
    'salon.guide1.title': 'Unfinished is perfect.',
    'salon.guide1.desc': 'This is a place to show the process, not just the polished product.',
    'salon.guide2.title': 'Celebrate small steps.',
    'salon.guide2.desc': 'A new button, finding a name—every little progress counts.',
    'salon.guide3.title': 'Gentle feedback.',
    'salon.guide3.desc': 'Offer opinions that help creators take their next step gracefully.',
    'salon.guide4.title': 'No self-promotion pressure.',
    'salon.guide4.desc': 'You don\'t need to sound like a marketer here. Just be a creator.',
    'salon.testSupporter': 'Test: View as Supporter',
    'salon.testPro': 'Test: View as Pro',
    'salon.testFree': 'Test: View as Free',
    'salon.progressBadge': 'Progress',
    'salon.questionBadge': 'Consultation',
    'salon.modeToggle.progress': 'Progress Update',
    'salon.modeToggle.question': 'Ask Question',
    'salon.publishing': 'Publishing...',
    'salon.publishFailed': 'Failed to post. Try again.',
    'salon.publishSuccess': 'Posted!',
    'salon.postFailedHint': 'Could not plant it well. Your words are saved, so please try again in a moment.',
    'salon.cheer': 'Cheer',
    'salon.cheered': 'Cheered',
    'salon.viewComments': 'Comments',
    'salon.writeComment': 'Write a gentle comment...',
    'salon.applyBoost': 'Apply for Light',
    'salon.boostApplied': 'Applied',
    'salon.boostCandidate': 'Light Candidate',
    'salon.postSuccessHint': 'A small step was planted. You can wait for reactions here, or ',
    'salon.postSuccessHintAction': 'apply for some light',
    'salon.postSuccessHintQuestion': 'Your thoughts were placed. Let\'s wait for someone to notice.',
    'salon.submitComment': 'Send',
    'salon.reply': 'Reply',
    'salon.loadingPosts': 'Loading greenhouse...',
    'salon.noPosts': 'No saplings here yet.',
    'salon.planNeededToPost': 'You need a Pro plan to post here.',
    'salon.planRequirement': 'This area is for Supporter & Pro members.',
    'salon.confirmDelete': 'Delete this post?',
    'salon.postsLoaded': 'Greenhouse sync complete.',
    'salon.postMine': 'You',
    'salon.edit': 'Edit',
    'salon.delete': 'Delete',
    'salon.freeGateTitle': 'Login to enter the Greenhouse',
    'salon.freeGateDesc': 'During beta, the Greenhouse is open to all logged-in users. Read works in progress, leave gentle comments, and share your own small steps.',
    'salon.freeGateBtn': 'Log in and enter',
    'salon.freeGateAccess': 'Reading and posting require login during beta.',
    'ai.betaQuota': 'Beta AI helpers are limited to {count} uses per day.',
    'pricing.perMonth': ' / month',
    'pricing.feature.postIdea': 'Create 1-3 idea pages',
    'pricing.feature.postSapling': 'Public idea page and basic profile',
    'pricing.feature.comments': 'Normal share button',
    'pricing.feature.basicProfile': 'Growth Agent trial (1/mo)',
    'pricing.feature.devLog': 'More idea posting and dev logs',
    'pricing.feature.aiSummarize': 'Growth Agent up to 10 times / month',
    'pricing.feature.boost': 'Tester Strategy and Share Boost',
    'pricing.feature.greenhouseAccess': 'Greenhouse access and Supporter badge',
    'pricing.feature.unlimited': 'Growth Agent up to 50 times / month',
    'pricing.feature.report': 'Store Review Readiness',
    'pricing.feature.lightConsult': 'Share Boost variants and SEO / OGP copy',
    'pricing.feature.testerBoost': 'Tester recruitment boost + 1 priority boost / month',
    'pricing.oneTimeBoost': 'Visibility Boost (7 days)',
    'pricing.oneTimeReport': 'AI Deep Review',
    'pricing.oneTimeTesters': 'Tester Recruitment Boost',
    'pricing.compareBtn': 'Compare Plans',
    'pricing.plan.free': 'Free Plan',
    'pricing.plan.supporter': 'Supporter Plan',
    'pricing.plan.pro': 'Pro Plan',
    'pricing.faq.q1': 'What is the "Greenhouse space"?',
    'pricing.faq.a1': 'It\'s a gentle space for rough ideas, daily progress, and casual doubts. During beta, any logged-in user can join; paid plans add visibility and extra support rather than a hard gate.',
    'pricing.faq.q2': 'What exactly is the "Boost" feature?',
    'pricing.faq.a2': 'It\'s a feature that brings your "sapling" app (WIP) back to the spotlight. We shine a light on projects that are making steady progress, giving them a chance to be rediscovered by the community.',
    'pricing.faq.q3': 'Can I change my plan midway?',
    'pricing.faq.a3': 'Yes, you can upgrade or downgrade at any time. Changes will be applied to the next billing cycle.',
    'pricing.faq.q4': 'Are there one-time purchase options?',
    'pricing.faq.a4': 'Yes. You can purchase the current boost and AI review items individually without a monthly subscription. Store Review Readiness is included in Pro.',
    'nav.language': '日本語',
    'idea.support': 'Support Idea',
    'idea.supported': 'Supported',
    'idea.joinTest': 'Join Tester Program',
    'idea.buildThis': 'I want to build this',
    'idea.share': 'Share',
    'idea.overview': 'Overview',
    'idea.wireframes': 'Wireframes',
    'idea.discussion': 'Discussion',
    'idea.problem': 'The Problem',
    'idea.audience': 'Target Audience',
    'idea.alternatives': 'Why Alternatives Fail',
    'idea.frustrations': 'Main Frustrations',
    'idea.mustHaves': 'Must-Haves',
    'idea.translateContent': 'Multi-language (AI)',
    'idea.emptyDiscussion': 'This idea is still young. Add a need, thought, or suggestion.',
    'idea.postComment': 'Post',
    'idea.loginComment': 'You must be logged in to post a comment.',
    'idea.loginButton': 'Log in to Join Discussion',
    'idea.wireframesMVP': 'Wireframes & MVP Scope',
    'idea.addSketch': 'Add Sketch',
    'idea.noWireframes': 'No wireframes yet',
    'idea.noWireframesDesc': 'Upload low-fidelity sketches or describe the screen flow to help builders understand your vision.',
    'idea.uploadImage': 'Upload Image',
    'idea.commentPlaceholder': 'Add your thoughts or suggestions...',
    'idea.aiAnalysisTitle': 'AI Summary Snapshot',
    'idea.aiAnalyzeBtn': 'Analyze Reactions with AI',
    'idea.aiPaidFeature': '※Paid feature (single purchase)',
    'idea.pastAiAnalyses': 'Past AI Analyses',
    'idea.builderActivity': 'Builder Activity',
    'idea.buildersInterested': 'interested',
    'idea.buildersInterestedDesc': 'Some developers have indicated they are looking into building a prototype.',
    'idea.noBuilders': 'No developers have claimed this yet.',
    'idea.firstToBuild': 'Be the first to build',
    'time.yearsAgo': 'years ago',
    'time.monthsAgo': 'months ago',
    'time.daysAgo': 'days ago',
    'time.hoursAgo': 'hours ago',
    'time.minsAgo': 'mins ago',
    'time.secondsAgo': 'seconds ago',
    'time.justNow': 'just now',
    'explore.title': 'Explore Ideas',
    'explore.subtitle': 'Discover problems waiting to be solved. Support your favorites, add your perspective, or find your next indie project.',
    'explore.allStages': 'All Stages',
    'explore.filters': 'Filters',
    'explore.mostSupported': 'Most Supported',
    'explore.search': 'Search for apps, tags, or problems...',
    'submit.title': 'Plant an Idea',
    'submit.subtitle': "Don't worry about being perfect. Just drop a seed of what you wish existed.",
    'submit.subtext': "Even a single line is enough. Let's grow it together.",
    'submit.submitBtn': 'Plant this Seed',
    'submit.submitHint': 'You can always edit and grow this later.',
    'submit.successTitle': 'Your idea is planted!',
    'submit.successDesc': "It's out there. The community will start reviewing it soon. We'll notify you when people support or comment on it.",
    'submit.successExplore': 'Explore other ideas',
    'submit.successProfile': 'View my profile',
    'submit.enhancing': 'Organizing...',
    'submit.enhance': 'Organize with AI',
    'submit.enhanceHint': 'Even brief thoughts are fine. AI will help shape them.',
    'submit.aiLimitReached': 'Today\'s beta AI helper limit has been reached. Please try again tomorrow.',
    'submit.nameLabel': 'Idea Name',
    'submit.namePlaceholder': 'e.g., A reading cafe map just for rainy days',
    'submit.summaryLabel': 'One-line Summary',
    'submit.summaryPlaceholder': 'e.g., A virtual accessory shop to enjoy the vibe before buying',
    'submit.audienceLabel': 'Who might like this?',
    'submit.audiencePlaceholder': 'e.g., People who are busy but want to dream a little',
    'submit.moreDetails': 'Add More Details (Optional)',
    'submit.problemLabel': "What's the challenge?",
    'submit.problemPlaceholder': 'What specific issue does this solve?',
    'submit.alternativesLabel': 'How is it handled now?',
    'submit.alternativesPlaceholder': 'Current alternatives...',
    'submit.frustrationsLabel': "What's missing?",
    'submit.frustrationsPlaceholder': 'Why are the current methods not enough?',
    'submit.minFeaturesLabel': 'Core idea for version 1',
    'submit.minFeaturesPlaceholder': 'What is the absolute minimum needed?',
    'submit.tagsLabel': 'Tags (Optional)',
    'submit.tagsPlaceholder': 'e.g., productivity, ios, community',
    
    'common.back': 'Back',
    'common.allGrowthRecords': 'View all growth records',
    'common.linkCopied': 'Link copied to clipboard!',
    'common.loading': 'Loading...',
    'common.ideaNotFound': 'Idea not found',
    'common.searchNoResults': 'No ideas found',
    'common.searchNoResultsDesc': "We couldn't find any ideas matching your criteria.",
    'common.clearFilters': 'Clear filters',
    'common.loginToPost': 'Log in to Post Idea',
    // Mode Selection
    'submit.mode.title': 'What are you bringing?',
    'submit.mode.seed': 'Plant a Seed',
    'submit.mode.seedDesc': 'Got a wish or a problem? Start with a simple thought and let the community help it grow.',
    'submit.mode.sapling': 'Bring a Sapling',
    'submit.mode.saplingDesc': 'Already working on something? Share your prototype or WIP app to get feedback and early testers.',
    
    // Sapling Form
    'submit.sapling.title': 'Bring a Sapling',
    'submit.sapling.subtitle': "It doesn't have to be finished. Even a mockup or a partial prototype is a great way to start gathering real feedback.",
    'submit.sapling.nameLabel': 'App / Prototype Name',
    'submit.sapling.summaryLabel': 'One-line Summary',
    'submit.sapling.whatItDoesLabel': 'What does it do?',
    'submit.sapling.whatItDoesPlaceholder': 'e.g., Grocery list that sorts by aisle. Briefly explain the core value.',
    'submit.sapling.audienceLabel': 'Who is it for?',
    'submit.sapling.statusLabel': 'Current Status',
    'submit.sapling.statusMock': 'Mockups / Design only',
    'submit.sapling.statusProto': 'Clickable Prototype',
    'submit.sapling.statusMvp': 'Functional MVP',
    'submit.sapling.statusTesting': 'In Beta / Testing',
    'submit.sapling.lookLabel': 'What feedback do you want?',
    'submit.sapling.lookDirection': 'Overall Direction',
    'submit.sapling.lookUsability': 'Usability & UI',
    'submit.sapling.lookDesign': 'Visual Design',
    'submit.sapling.lookNeeds': 'Missing Features',
    'submit.sapling.lookTesters': 'Looking for Testers',
    'submit.sapling.urlLabel': 'Demo URL (Optional)',
    'submit.sapling.urlHint': 'Link to a prototype, TestFlight, or live demo.',
    'submit.demoUrlLabel': 'Demo URL (Optional)',
    'submit.demoUrlPlaceholder': 'https://...',
    'submit.sapling.screenshotsLabel': 'Screenshots (Optional)',
    'submit.sapling.screenshotsHint': 'Upload 1-3 screenshots to show the vibe.',
    'submit.sapling.screenshotsNotice': 'Image upload is in preparation. You can post with just a URL for now!',
    'submit.sapling.strugglesLabel': 'Current struggles & feedback needs',
    'submit.sapling.strugglesPlaceholder': 'e.g., Not sure if this UI is intuitive / Looking for feedback on color palette.',
    'submit.sapling.submitBtn': 'Post this Sapling',
    
    'idea.saplingBadge': 'WIP App',
    'idea.tryPrototype': 'Try the Prototype',
    'idea.whatItDoes': 'What it does',
    'idea.currentStatus': 'Current Status',
    'idea.lookingFor': 'Looking for feedback on:',
    'idea.struggles': 'Current Struggles',
    'idea.viewApp': 'View the App',
    'idea.hasBoreFruit': 'This Idea has Borne Fruit!',
    'idea.originSeed': 'Grown from this Seed',
    'idea.originSapling': 'This Sapling has been Released',
    'idea.grownFrom': 'This idea reached the world with community support.',
    'idea.growthLog': 'The Growth Journey',
    'idea.atSeed': 'Idea Planted',
    'idea.atSeedDesc': 'The first step. The idea was planted in the community.',
    'idea.atSapling': 'Sprouted as Sapling',
    'idea.atSaplingDesc': 'Development started and became a tangible prototype.',
    'idea.atGrowing': 'Growing with Feedback',
    'idea.atTesting': 'Testing Phases',
    'idea.atTestingDesc': 'Multiple testing phases and refinements with community feedback.',
    'idea.atReleased': 'Full Bloom',
    'idea.atReleasedDesc': 'A real app has been released thanks to the App Gardenium community!',
    'home.shippedTitle': 'Recently Borne Fruit',
    'home.shippedDesc': 'Ideas and saplings that have successfully turned into real apps.',
    'footer.tagline1': 'A place to nourish the seeds of solo development.',
    'footer.tagline2': 'Start small, grow together.',
    'footer.support': 'Support',
    'footer.terms': 'Terms of Service',
    'footer.privacy': 'Privacy Policy',
    'footer.commerce': 'Commercial Disclosure',
    'footer.contact': 'Contact Us',
    'footer.creator': 'Creator',
    'footer.builtBy': 'Built by {name}.',
    'footer.betaNotice': 'App Gardenium is currently in beta. There may be bugs or changes, but we will gradually improve the garden based on your feedback.',
    'tester.recruitTitle': 'Recruit Testers',
    'tester.recruitSubtitle': "Ready to put your prototype in the hands of real users? Let's create a clear call for testers.",
    'tester.backToProfile': 'Back to My Page',
    'tester.step1.title': 'WHICH IDEA ARE YOU RECRUITING FOR?',
    'tester.step1.select': 'Select an idea...',
    'tester.step1.stageLabel': 'WHAT STAGE IS YOUR PROTOTYPE?',
    'tester.stage.mockup': 'Clickable Mockup',
    'tester.stage.mockupDesc': 'Figma, Protopie, etc.',
    'tester.stage.alpha': 'Alpha Build',
    'tester.stage.alphaDesc': 'Rough, but works.',
    'tester.stage.beta': 'Private Beta',
    'tester.stage.betaDesc': 'Polished, near launch.',
    'tester.nextStep': 'Next Step',
    'tester.step2.whoLabel': 'Who is the ideal tester?',
    'tester.step2.whoHint': 'Be specific! (e.g., "Freelance designers using Mac", "Dog owners who walk daily")',
    'tester.step2.whoPlaceholder': 'Target profile...',
    'tester.step2.whatLabel': 'What exactly do you want to test?',
    'tester.step2.whatHint': 'Are you testing usability? Pricing? Whether a specific feature makes sense?',
    'tester.step2.whatPlaceholder': 'E.g., I want to know if the onboarding flow is confusing. Try to set up a new project without looking at the guide.',
    'tester.step2.linkLabel': 'Action Link (Optional)',
    'tester.step2.linkPlaceholder': 'figma.com/file/...',
    'tester.back': 'Back',
    'tester.postBtn': 'Post Recruitment',
    'tester.submitting': 'Posting...',
    'tester.loadingIdeas': 'Loading your ideas...',
    'tester.noIdeas': 'Post an app idea first, then come back here to recruit testers.',
    'tester.fetchError': 'Could not load your ideas. Please refresh and try again.',
    'tester.postError': 'Could not post the tester recruitment. Please check the idea and try again.',
    'moderation.report': 'Report',
    'moderation.reportPrompt': 'What should we review? Optional details help the moderator.',
    'moderation.reportSent': 'Reported',
    'moderation.confirmDelete': 'Delete this content permanently?',
    'admin.title': 'Admin: Moderation',
    'admin.desc': 'Review user reports, hide harmful public content, and manage boost applications.',
    'admin.forbiddenTitle': 'Admin access required',
    'admin.forbiddenDesc': 'This page is only available to administrators.',
    'admin.reportsTitle': 'User reports',
    'admin.noReports': 'No open reports right now.',
    'admin.noDetails': 'No additional details provided.',
    'admin.hide': 'Hide',
    'admin.delete': 'Delete',
    'admin.dismiss': 'Dismiss',
    'admin.boostsTitle': 'Boost applications',
    'admin.noBoosts': 'There are no boosts waiting for approval currently.',
    'admin.approve': 'Approve',
    'admin.reject': 'Reject',
  },
  ja: {
    'home.label': 'アプリの「あったらいいな」が集まる場所',
    'home.hero': 'アプリのアイデアを、みんなで育てる。',
    'home.subhero': 'App Gardenium は、アプリのアイデアをみんなで育てる小さな庭です。\nまだβ版ですが、投稿、感想、応援、不具合報告のひとつひとつが、この場所を少しずつ育てていきます。',
    'home.exploreBtn': 'アイデアを探す',
    'home.postBtn': 'アイデアを置く',
    'home.howItWorks': 'タネが育つ流れ',
    'home.step1Title': 'タネをまく',
    'home.step1Desc': '「あったらいいな」をひとこと置くだけでOK。技術がなくても大丈夫。まずは困りごとや願いを言葉にしてみましょう。',
    'home.step2Title': '水をかかさない',
    'home.step2Desc': 'コミュニティの反応や応援に触れることで、アイデアが少しずつ形になり、独りよがりではない「求められる案」へ育ちます。',
    'home.step3Title': '実を結ぶ',
    'home.step3Desc': '育ったアイデアを開発者が形にし、テスターと出会う。App Gardenium は、最後の一歩までをサポートします。',
    'home.sproutingTitle': 'いま動きはじめたタネ',
    'home.sproutingDesc': '反応が集まり、少しずつ育ちはじめたアイデアです。',
    'home.viewAll': 'もっと見る',
    'home.devTitle': 'つくる人へ',
    'home.devDesc': '誰にも求められていないものを作る不安があるなら、まずは育ったアイデアを見てみませんか？実際の願いから開発の種を見つけられます。また、すでに作りかけのアプリ（苗）を持ち込んでブラッシュアップするのも大歓迎です！',
    'home.devBtn': 'つくるアイデアを探す',
    'home.testerTitle': '試してみたい人へ',
    'home.testerDesc': '開発中のアプリをいち早く試して、フィードバックを届けましょう。未来のツールづくりに直接関われます。',
    'home.testerBtn': 'テスターとして参加',
    'home.loadingIdeas': 'アイデアを読み込み中...',
    'home.shippedEmptyDesc': '温室スペースで、いくつかのアイデアが静かに芽吹いています。コミュニティから生まれたアプリが、まもなくここに並びます。',
    'home.shippedEmptyBtn': '開発のタネを探しに行く',
    'stage.seed': 'タネ（アイデア）',
    'stage.sprout': '苗（プロトタイプ）',
    'stage.growing': '育成中',
    'stage.testing': 'テスト中',
    'stage.polishing': '磨き込み中',
    'stage.launching': '公開準備中',
    'stage.released': '実りました',
    'stage.archived': 'アーカイブ済み',
    'nav.explore': 'みつける',
    'nav.home': 'ホーム',
    'nav.submit': 'アイデアを植える',
    'nav.login': 'ログイン',
    'nav.profile': 'プロフィール',
    'nav.pricing': '料金プラン',
    'nav.salon': '温室',
    'login.titlePrefix': 'ようこそ',
    'login.subtitle': '作り手と夢見る人たちのコミュニティへ。みんなでアイデアを育てていきましょう。',
    'login.signingIn': 'ログイン中...',
    'login.continueGoogle': 'Googleで続ける',
    'login.termsPrefix': '続行すると、',
    'login.termsAnd': ' と ',
    'login.termsSuffix': ' に同意したものとみなされます。',
    'login.error.popupBlocked': 'ログイン用ポップアップがブロックされました。ページ遷移での Google ログインを試します。',
    'login.error.network': 'ログイン中に通信エラーが発生しました。接続を確認して再度お試しください。',
    'login.error.unauthorizedDomain': 'このドメインは Google ログインにまだ許可されていません。Firebase Authentication の設定を確認してください。',
    'login.error.generic': 'いまはログインできませんでした。少しおいて再度お試しください。',
    'status.public': '公開',
    'status.private': '非公開',
    'status.pending': '処理中',
    'status.paid': '支払い済み',
    'status.fulfilled': '提供済み',
    'status.failed': '失敗',
    'commerce.legalTitle': '特定商取引法に基づく表記',
    'commerce.back': 'ショップへ戻る',
    'common.you': 'あなた',
    'common.anonymous': '匿名ユーザー',
    'common.sproutThinker': '芽を出す人',
    'common.sproutBuilder': '育てる人',
    'profile.editProfile': 'プロフィール編集',
    'profile.displayName': '表示名',
    'profile.bio': '自己紹介',
    'profile.bioPlaceholder': 'あなたのことや、興味のあることを教えてください...',
    'profile.skills': 'スキル（カンマ区切り）',
    'profile.skillsPlaceholder': '例: React, デザイン, マーケティング',
    'profile.twitter': 'Twitter',
    'profile.github': 'GitHub',
    'profile.website': 'ウェブサイト',
    'profile.cancel': 'キャンセル',
    'profile.save': '保存',
    'profile.growingSince': '活動開始時期：',
    'profile.recently': '最近',
    'profile.ideas': 'アイデア',
    'profile.supported': '応援',
    'profile.comments': 'コメント',
    'profile.testsJoined': 'テスト参加',
    'profile.plantedIdeas': '自分のアイデア',
    'profile.supportedIdeas': '応援したアイデア',
    'profile.builtApps': '開発したアプリ',
    'profile.addApp': 'アプリを追加',
    'profile.recruitTesters': 'テスターを募集',
    'profile.addAppTitle': '開発したアプリを登録する',
    'profile.appNameLabel': 'アプリ名',
    'profile.appDescLabel': 'アプリの概要',
    'profile.appUrlLabel': 'アプリのURL',
    'profile.addAppSubmit': 'アプリを保存',
    'profile.nothingBuilt': 'まだ開発したアプリはありません',
    'profile.nothingBuiltDesc': '気になるアイデアから開発のヒントを見つけて、形にしてみましょう。',
    'profile.noIdeas': 'まだタネがありません',
    'profile.noIdeasDesc': 'あなたの「あったらいいな」を置いてみませんか？',
    'profile.noSupported': 'まだ応援したアイデアがありません',
    'profile.noSupportedDesc': '誰かのタネに反応を届けることから始めてみませんか？',
    'profile.startPlanted': '最初のアイデアを置く',
    'profile.startExplore': '開発のタネを探す',
    'profile.startSalon': '温室スペースをのぞく',
    'profile.logout': 'ログアウト',
    'profile.visitApp': 'アプリを見る',
    'profile.avatarModerationError': '不適切な画像が検出されました。別の画像を選択してください。',
    'commerce.aiTickets': '育成のしおり（AI機能）',
    'commerce.balance': '残り',
    'commerce.topup.title': '単発メニュー',
    'commerce.topup.desc': '無料プランでも、必要なものだけ単発で追加できます。',
    'membership.topup.title': '単発メニュー',
    'membership.topup.desc': '月額プランがなくても、必要な後押しだけ単発で追加できます。',
    'membership.topup.boost.title': '表示ブースト 7日間',
    'membership.topup.boost.desc': 'アイデアページをもう一度見つけてもらいやすくします。',
    'membership.topup.boost.status': '今月 {count}回',
    'membership.topup.boost.button': '{price}で追加',
    'membership.topup.report.title': 'AI深掘りレビュー',
    'membership.topup.report.desc': '方向性や次の一歩を、AIで1回深く整理します。',
    'membership.topup.report.status': '残り {count}回',
    'membership.topup.report.button': '{price}で追加',
    'membership.topup.tester.title': 'テスター募集ブースト',
    'membership.topup.tester.desc': '1回分のテスター募集を強化し、初期ユーザーを集めやすくします。',
    'membership.topup.tester.status': '残り {count}回',
    'membership.topup.tester.button': '{price}で追加',
    'commerce.balanceUnit': '回分',
    'commerce.ticketDesc': 'アイデアを整理したり、反応を要約したり。AIがあなたの育成を補助します。',
    'commerce.instantFulfillment': '即時付与',
    'commerce.footerTicketDesc': '購入後、すぐにAI機能の実行に使用できます。',
    'commerce.confirmPurchase': '購入内容の確認',
    'commerce.proceedToPurchase': '購入へ進む',
    'commerce.purchaseAmount': '購入金額',
    'commerce.deliveryTiming': '提供時期',
    'report.title': 'AI分析レポート',
    'report.generatedBy': 'AIによる分析',
    'report.summaryLabel': '反応の要約',
    'report.commonRequestsLabel': 'よく出ている要望',
    'report.concernsLabel': '気になられている点',
    'report.nextActionsLabel': '次に直す候補 (AI推奨)',
    'report.analyzedAt': '分析日時',
    'report.onlyLatestDesc': '最新の反応のみを分析しています',

    // Membership / Billing Management
    'membership.title': '会員プランと管理',
    'membership.currentPlan': '現在のプラン',
    'membership.status': '会員状態',
    'membership.status.active': '有効',
    'membership.status.pending': '反映待ち',
    'membership.status.canceled': '解約済み',
    'membership.status.past_due': 'お支払いの確認が必要です',
    'membership.status.inactive': '未加入',
    'membership.status.free': '無料ユーザー',

    // Membership State Details
    'membership.state.active.label': '有効です',
    'membership.state.active.desc': 'いまの会員特典を利用できます。',
    'membership.state.pending.label': '反映待ちです',
    'membership.state.pending.desc': 'お支払いは完了していますが、会員状態の反映に少し時間がかかることがあります。数秒後にページを更新してください。',
    'membership.state.renewing.label': '継続中です',
    'membership.state.renewing.desc': 'このプランは毎月自動で更新されます。',
    'membership.state.payment_issue.label': 'お支払いの確認が必要です',
    'membership.state.payment_issue.desc': 'お支払い方法の確認が必要です。このまま反映されない場合、会員特典が使えなくなることがあります。',
    'membership.state.cancel_scheduled.label': '解約予定です',
    'membership.state.cancel_scheduled.desc': '現在の期間が終わるまで、引き続き会員特典を利用できます。',
    'membership.state.canceled.label': '解約済みです',
    'membership.state.canceled.desc': '現在は無料プランとして利用できます。必要になったら、またいつでも会員席を選べます。',
    'membership.state.expired.label': '無料プランに戻りました',
    'membership.state.expired.desc': '現在の会員特典は終了しましたが、β期間中の温室や日ごとのAI補助を含め、無料でも引き続きご利用いただけます。',

    'membership.manage': 'プランの管理',
    'membership.payment': '支払い方法の確認',
    'membership.cancel': '解約の手続き',
    'membership.perks': 'この席で使えること',
    'membership.greenhouse': '温室スペースを見に行く',
    'membership.post': '進捗を投稿する',
    'membership.reflectNotice': '支払い完了後、反映まで少し時間がかかる場合があります。',
    'membership.upgradePro': 'Pro にアップグレードする',
    'membership.upgradeSupporter': 'Supporter をはじめる',
    'membership.billingHistory': '請求履歴',
    'membership.changePayment': '支払い情報を変更する',
    'membership.portalDesc': 'Stripe の安全な管理画面で、サブスクリプションの管理や請求履歴の確認、支払い方法の変更ができます。',
    'membership.openPortal': '管理ポータルを開く',
    'membership.startedAt': '利用開始日',
    'membership.nextStep': '次の一歩',
    'membership.reloadStatus': '状態を再読み込み',
    'membership.keepFree': '無料で使い続ける',
    'membership.checkRenewal': '更新日を確認する',

    'billing.currentPlan': '現在のプラン',
    'billing.startThisPlan': 'このプランをはじめる',
    'billing.managePlan': 'プランを管理する',
    'billing.upgrade': 'Pro にアップグレード',
    'billing.confirm.header': '購入内容を確認してから進みます',
    'billing.confirmJoin': '{plan} に参加する',
    'billing.confirmDesc': 'App Gardenium の庭をサポートしますか？\nこの支援は、β版の運営・改善・AI生成費の維持に使われます。',
    'billing.billingCycle': '月額料金',
    'billing.proceedToCheckout': '内容を確認して購入に進む',
    'billing.termsAgreement': '手続きを進めることで、利用規約およびプライバシーポリシーに同意したものとみなされます。',
    'billing.viewLegal': '特定商取引法に基づく表記を見る',
    'billing.confirm.legalNote': '購入前に販売条件をご確認ください。キャンセル・返金については、特定商取引法に基づく表記をご確認ください。',
    'billing.processing': '処理中...',
    'billing.successTitle': 'ご加入ありがとうございます！',
    'billing.successSubSupporter': 'Supporter へようこそ。アイデアを続けて育てるための席が、少し整いました。',
    'billing.successSubPro': 'Pro へようこそ。ここから公開準備に近づけていきましょう。',
    'billing.reflectingNotice': '支払い完了後、会員特典の反映に少し時間がかかる場合があります。',
    'billing.unlockedFeatures': '新しく使えるようになったこと',
    'billing.startHere': 'まずはここから',
    'billing.startHerePro': '最初の一歩を踏み出す',

    // Plan Confirmation Details - Supporter
    'plan.supporter.confirmTitle': 'Supporter をはじめる',
    'plan.supporter.confirmSub': '少しずつ育て続けるための席です。投稿の余白を増やし、Growth Agent を月10回まで使いながら、テスター募集やシェア文の下書きを整えられます。',
    'plan.supporter.price': '月額 ¥300（税込）',
    'plan.supporter.cycle': '毎月自動更新です',
    'plan.supporter.note': 'まずは読むところからでも大丈夫です。',
    'plan.supporter.f1': 'Supporter バッジが反映されます',
    'plan.supporter.f2': 'アイデア投稿数と開発ログの余白が増えます',
    'plan.supporter.f3': 'Growth Agent を月10回まで使えます',
    'plan.supporter.f4': 'Tester Strategy と Share Boost の下書きを作れます',
    'plan.supporter.f5': '温室での存在感が少し上がり、育て続けやすくなります',

    // Plan Confirmation Details - Pro
    'plan.pro.confirmTitle': 'Pro をはじめる',
    'plan.pro.confirmSub': '公開準備まで進めたい人のための席です。次アクション整理、ストア審査リスク診断、シェア文やSEO文の準備まで一気通貫で進めやすくなります。',
    'plan.pro.price': '月額 ¥980（税込）',
    'plan.pro.cycle': '毎月自動更新です',
    'plan.pro.note': '育てる段階から、公開に近づく段階へ進みたい人向けです。',
    'plan.pro.f1': 'Pro バッジが反映されます',
    'plan.pro.f2': 'Growth Agent を月50回まで使えます',
    'plan.pro.f3': 'Store Review Readiness を使えます',
    'plan.pro.f4': 'Share Boost 複数案と SEO / OGP 文を整えられます',
    'plan.pro.f5': 'テスター募集を強化し、見つけてもらいやすさを上げられます',
    'plan.pro.f6': '月1回の優先ブーストが含まれます',
    
    // Steps - Supporter
    'billing.step.supporter1.title': 'アイデアをもう少し置く',
    'billing.step.supporter1.desc': 'ひとつに詰め込みすぎず、育てたい案を少し広めに持てます',
    'billing.step.supporter2.title': 'Growth Agent を回す',
    'billing.step.supporter2.desc': 'テスター募集やシェア文の方向性を、軽く何度も整えられます',
    'billing.step.supporter3.title': '続ける流れを作る',
    'billing.step.supporter3.desc': 'ログや温室を使いながら、途中で止まりにくい形にしていきます',
    
    // Steps - Pro
    'billing.step.pro1.title': '公開向けレビューを回す',
    'billing.step.pro1.desc': 'Growth Agent、Store Review Readiness、Share Boost を1つの案に重ねられます。',
    'billing.step.pro2.title': '見せ方を整える',
    'billing.step.pro2.desc': 'テスター募集文、シェア文、SEO / OGP 文をまとめて準備できます。',
    'billing.step.pro3.title': '公開に近づける',
    'billing.step.pro3.desc': '月1回の優先ブーストと次アクション整理で、リリース前進を作ります',

    // Actions
    'billing.action.viewGreenhouse': '温室スペースを見に行く',
    'billing.action.postProgress': '進捗を投稿する',
    'billing.action.goHome': 'ホームへ戻る',
    'billing.action.viewProfile': 'プロフィールを確認する',

    // Cancel
    'billing.cancelTitle': '手続きを中断しました',
    'billing.cancelDesc': 'App Gardenium は無料でも、あなたのペースで自由に使えます。また必要になったら、いつでも会員席を選んでみてください。',
    'billing.backToPricing': '料金ページへ戻る',
    'pricing.badge': 'あなたの開発ペースに合わせて選べます',
    'pricing.heroTitle': 'アイデアの芽から、公開準備まで。',
    'pricing.heroSub': 'まずは無料ではじめて、必要になったら Growth Agent、テスター募集、ストア審査準備、シェア文づくりまで少しずつ足していけます。',
    'pricing.plan.freeShort': 'まずは種を置く。',
    'pricing.plan.freeTitle': 'まずは種を置く',
    'pricing.plan.freeDesc': 'アイデアを置き、公開ページを作り、反応が返ってくるかを見てみるところから。',
    'pricing.plan.freeNote': '最初の一歩は、軽くて大丈夫です。',
    'pricing.plan.supporterShort': '育て続ける。',
    'pricing.plan.supporterTitle': '育て続ける',
    'pricing.plan.supporterDesc': 'ひとつの案を止めずに育てるために。Growth Agent や Share Boost を少し多めに使える席です。',
    'pricing.plan.supporterNote': '続けるための、やさしい月額席。',
    'pricing.plan.supporterTag': '育成サポート',
    'pricing.plan.proShort': '公開に近づける。',
    'pricing.plan.proTitle': '公開準備まで進める',
    'pricing.plan.proDesc': '募集、審査準備、シェア導線まで整えながら、リリースに近づくための席です。',
    'pricing.plan.proNote': '育てる段階から、公開へ進みたい人に。',
    'pricing.plan.proTag': '公開・募集・審査準備',
    'pricing.whoFree': 'まずはアイデアを置いて、反応があるか試したい人。',
    'pricing.whoSupporter': 'ひとつのアイデアを、AIの助けを借りながら継続的に育てたい人。',
    'pricing.whoPro': 'テスター募集や審査準備まで進めて、公開に近づきたい人。',
    'pricing.salonTitle': '会員限定の「温室スペース」',
    'pricing.salonDesc': '小さな進捗も、迷いも、途中経過も。ひとりで抱え込みすぎず、メンバー間で共有できる場所です。',
    'pricing.salonSupporterSub': 'まずは読むところから。',
    'pricing.salonSupporterDesc': 'β期間中の温室はログインユーザー全員に開放中。Supporter は、その場を支えつつ存在感を少し出しやすくする席です。',
    'pricing.salonProSub': '進捗を、もう少し届きやすく。',
    'pricing.salonProDesc': 'β期間中はログインしていれば投稿できます。Pro は、見つけてもらいやすさやブースト準備など、前に進みやすい道具を足す席です。',
    'pricing.boostTitle': '必要なときだけ、ひかりをあてる',
    'pricing.boostDesc': '埋もれがちな途中経過にも、もう一度見つけてもらうきっかけを。ブーストは、目立たせるためではなく、育ちやすくするための機能です。',
    'pricing.boostSupporterSub': 'Supporter: まずは育てる後押し',
    'pricing.boostSupporterDesc': 'Growth Agent や Share Boost を少し多めに使いながら、止まらず育てる流れを作れます。',
    'pricing.boostProSub': 'Pro: 公開に向けた後押し',
    'pricing.boostProDesc': 'Store Review Readiness、強化された Share Boost、月1回の優先ブーストで公開に近づけます。',
    'pricing.ctaTitle': 'すべては、一粒のタネから。',
    'pricing.ctaSubtitle': 'まずは無料で、はじめてみませんか？',
    'pricing.ctaDesc': 'アイデアを置いて、反応を待ってみる',
    'pricing.ctaBtn': '無料ではじめる',
    'pricing.initialCost': '初期費用 ¥0',
    'pricing.cancelAnytime': '解約いつでもOK',
    'pricing.footerNote': '個人開発者の静かな情熱と、ちいさなアイデアを支える。',
    'pricing.freeLabel': 'まずはここから',
    'pricing.supporterLabel': '育てる土を整える',
    'pricing.proLabel': '次の一歩へ進める',
    'pricing.startFree': '無料ではじめる',
    'pricing.becomeSupporter': 'Supporterになる',
    'pricing.startPro': 'Proではじめる',
    'pricing.whoIsItFor': 'こんな人に向いています',
    'pricing.comparison': 'プラン詳細比較',
    'pricing.oneTime': '必要なときだけ、ひかりをあてる',
    'pricing.oneTimeDesc': '必要なときだけ使える単発メニューです。ストア審査準備の診断は Pro に含まれます。',
    'pricing.faqTitle': 'よくある質問',
    'salon.title': '温室スペース（Greenhouse）',
    'salon.subtitle': '育ちかけを、安心して置ける場所。',
    'salon.desc': '小さな進捗も、毎日の迷いも、未完成のままで大丈夫。ひとりで抱え込まずに、少しずつ前に進みましょう。',
    'salon.supporterBadge': 'Supporter',
    'salon.proBadge': 'Pro',
    'salon.postIdea': '今日はどんな芽が出ましたか？',
    'salon.postIdeaHint': '完成してなくて大丈夫です。1枚のスクショや、ちょっとした迷いでも。',
    'salon.postBtn': '進捗を置く',
    'salon.postConsultBtn': '軽く相談する',
    'salon.upgradePromptTitle': '自分の進捗も置いてみませんか？',
    'salon.upgradePromptDesc': 'β期間中は、ログインしていれば誰でもここで投稿・コメント・リアクションできます。未完成のまま、やさしく混ざれる空気を大切にしています。',
    'salon.upgradeBtn': 'Proプランを見る',
    'salon.themeTitle': '今週のテーマ',
    'salon.themeDesc': 'もし迷ったら、こんなテーマで置いてみませんか？',
    'salon.themeTopic': '最初の1画面、どう見えてる？',
    'salon.themeCurrent': 'テーマ：10秒で伝わる工夫',
    'salon.wipTitle': '今週の育ちかけ',
    'salon.wipDesc': '少しずつ形になってきている、会員さんたちの最新の途中経過です。',
    'salon.wipEmpty': '今週の進捗はまだありません。',
    'salon.consultTitle': '軽い相談の苗床',
    'salon.consultDesc': '前へ進むため、重すぎない相談ごとが集まっています。',
    'salon.boostTitle': '今週のひかり',
    'salon.boostDesc': '着実に育っていて、もっと見つかってほしい途中経過たち。',
    'salon.guideTitle': 'この場所での過ごし方',
    'salon.guide1.title': '未完成のままでOK',
    'salon.guide1.desc': '完成品を披露する場所ではなく、過程を置く場所です。',
    'salon.guide2.title': '小さな一歩を大切に',
    'salon.guide2.desc': 'ボタンができた、名前が決まったなど、ささいな進捗も歓迎です。',
    'salon.guide3.title': '後押しになる反応を',
    'salon.guide3.desc': '鋭い指摘よりも、次に進みやすくなるような優しい視点を。',
    'salon.guide4.title': '宣伝しなくて大丈夫',
    'salon.guide4.desc': '見栄えを気にせず、ひとりの作り手としていられる場所です。',
    'salon.testSupporter': 'Supporter会員でプレビュー',
    'salon.testPro': 'Pro会員でプレビュー',
    'salon.testFree': '無料会員でプレビュー',
    'salon.progressBadge': '進捗報告',
    'salon.questionBadge': '気軽な相談',
    'salon.modeToggle.progress': '進捗を置く',
    'salon.modeToggle.question': '軽く相談する',
    'salon.publishing': '投稿中...',
    'salon.publishFailed': '投稿に失敗しました。再試行してください。',
    'salon.publishSuccess': '投稿しました！',
    'salon.postFailedHint': 'うまく置けませんでしたが、内容は残っています。少しおいて再度お試しください。',
    'salon.cheer': '応援',
    'salon.cheered': '応援しました',
    'salon.viewComments': 'コメント',
    'salon.writeComment': 'やさしい反応を書く...',
    'salon.applyBoost': 'ひかりをあてる候補に出す',
    'salon.boostApplied': '応募済み',
    'salon.boostCandidate': '今週のひかり候補',
    'salon.postSuccessHint': '小さな一歩を置きました。このまま少し待つか、',
    'salon.postSuccessHintAction': 'ひかりをあてる候補に出す',
    'salon.postSuccessHintQuestion': '相談を置きました。どなたかの反応を少し待ってみましょう。',
    'salon.submitComment': '送信',
    'salon.reply': '返信',
    'salon.loadingPosts': '温室を同期中...',
    'salon.noPosts': 'まだ何も置かれていないようです。',
    'salon.planNeededToPost': '投稿するには Pro プランが必要です。',
    'salon.planRequirement': 'このエリアは Supporter / Pro 会員専用です。',
    'salon.confirmDelete': 'この投稿を削除しますか？',
    'salon.postsLoaded': '温室のデータを読み込みました。',
    'salon.postMine': 'あなた',
    'salon.edit': '編集',
    'salon.delete': '削除',
    'salon.freeGateTitle': 'ログインして温室に入る',
    'salon.freeGateDesc': 'β期間中の温室スペースは、ログインユーザー全員に開放しています。育ちかけを読み、やさしく反応し、自分の小さな進捗も置けます。',
    'salon.freeGateBtn': 'ログインして入る',
    'salon.freeGateAccess': 'β期間中は、閲覧も投稿もログイン必須です。',
    'ai.betaQuota': 'β中のAI補助は、1日 {count} 回までです。',
    'pricing.perMonth': ' / 月',
    'pricing.feature.postIdea': 'アイデアを1〜3件投稿',
    'pricing.feature.postSapling': '公開ページと基本プロフィール',
    'pricing.feature.comments': '通常の共有ボタン',
    'pricing.feature.basicProfile': 'Growth Agent お試し（月1回）',
    'pricing.feature.devLog': '投稿数と開発ログの余白アップ',
    'pricing.feature.aiSummarize': 'Growth Agent 月10回',
    'pricing.feature.boost': 'Tester Strategy と Share Boost',
    'pricing.feature.greenhouseAccess': '温室参加と Supporter バッジ',
    'pricing.feature.unlimited': 'Growth Agent 月50回',
    'pricing.feature.report': 'Store Review Readiness',
    'pricing.feature.lightConsult': 'Share Boost 複数案と SEO / OGP 文',
    'pricing.feature.testerBoost': 'テスター募集強化 + 月1回の優先ブースト',
    'pricing.oneTimeBoost': '表示ブースト 7日間',
    'pricing.oneTimeReport': 'AI深掘りレビュー',
    'pricing.oneTimeTesters': 'テスター募集ブースト',
    'pricing.compareBtn': 'プランを比較する',
    'pricing.plan.free': '無料プラン',
    'pricing.plan.supporter': 'Supporterプラン',
    'pricing.plan.pro': 'Proプラン',
    'pricing.faq.q1': '「温室スペース」とは何ですか？',
    'pricing.faq.a1': 'ラフなアイデアや日々の進捗、ちょっとした迷いを置くためのやさしい場所です。β期間中はログインユーザーなら参加でき、有料プランは締め出しではなく、見つけてもらいやすさや補助を足す役目です。',
    'pricing.faq.q2': '「ブースト機能」とは具体的にどのようなものですか？',
    'pricing.faq.a2': '作りかけの「苗」アプリを、もう一度スポットライトが当たる場所に引き上げる機能です。着実に育っているプロジェクトに光を当てることで、コミュニティから再発見される機会を作ります。',
    'pricing.faq.q3': 'プランの変更は途中でできますか？',
    'pricing.faq.a3': 'はい、いつでもアップグレードやダウングレードが可能です。変更は次回の更新タイミングから適用されます。',
    'pricing.faq.q4': '単発で購入できるメニューはありますか？',
    'pricing.faq.a4': 'はい。現在のブーストやAIレビュー系メニューは、月額加入なしでも単発で利用できます。Store Review Readiness は Pro に含まれます。',
    'nav.language': 'English',
    'idea.support': '応援する',
    'idea.supported': '応援済み',
    'idea.joinTest': 'テスターに参加する',
    'idea.buildThis': '開発したい',
    'idea.share': 'シェア',
    'idea.overview': '概要',
    'idea.wireframes': 'ワイヤーフレーム',
    'idea.discussion': 'ディスカッション',
    'idea.problem': '解決したい課題',
    'idea.audience': 'ターゲット層',
    'idea.alternatives': '既存手段が不十分な理由',
    'idea.frustrations': '主な不満点',
    'idea.mustHaves': '必須要件 (Must-Haves)',
    'idea.translateContent': '自動翻訳 (AI)',
    'idea.emptyDiscussion': 'このアイデアはまだ生まれたばかりです。要望や感想、提案を加えてみましょう。',
    'idea.postComment': '投稿する',
    'idea.loginComment': 'コメントを投稿するにはログインが必要です。',
    'idea.loginButton': 'ログインして参加する',
    'idea.wireframesMVP': 'ワイヤーフレーム / MVPの範囲',
    'idea.addSketch': '下書きを追加',
    'idea.noWireframes': 'ワイヤーフレームがまだありません',
    'idea.noWireframesDesc': '手書きのスケッチをアップロードしたり、画面遷移を説明したりして、開発者がイメージを掴めるようにしましょう。',
    'idea.uploadImage': '画像をアップロード',
    'idea.commentPlaceholder': 'あなたの意見や提案を聞かせてください...',
    'idea.aiAnalysisTitle': 'AI 要約スナップショット',
    'idea.aiAnalyzeBtn': 'AIで反応を整理する',
    'idea.aiPaidFeature': '※有料機能（単発購入）です',
    'idea.pastAiAnalyses': '過去のAI分析',
    'idea.builderActivity': '開発者の動き',
    'idea.buildersInterested': '人が関心を持っています',
    'idea.buildersInterestedDesc': '複数の開発者がプロトタイプの作成を検討しています。',
    'idea.noBuilders': 'まだこのアイデアを担当する開発者はいません。',
    'idea.firstToBuild': '最初の開発者になる',
    'time.yearsAgo': '年前',
    'time.monthsAgo': 'ヶ月前',
    'time.daysAgo': '日前',
    'time.hoursAgo': '時間前',
    'time.minsAgo': '分前',
    'time.secondsAgo': '秒前',
    'time.justNow': 'たった今',
    'explore.title': 'アイデアを探す',
    'explore.subtitle': '解決されるのを待っている課題を見つけましょう。お気に入りを応援したり、あなたの視点を足したり、次の開発プロジェクトを見つけたりできます。',
    'explore.allStages': 'すべての段階',
    'explore.filters': 'フィルター',
    'explore.mostSupported': '支持が多い順',
    'explore.search': 'アプリ、タグ、課題を一発検索...',
    'submit.title': 'アイデアを植えよう',
    'submit.subtitle': '完璧じゃなくて大丈夫。まずは「あったらいいな」を置いてみよう。',
    'submit.subtext': 'ひとことだけでも、立派なタネになります。',
    'submit.submitBtn': 'まずはタネを置く',
    'submit.submitHint': 'あとで編集して、じっくり育てられます',
    'submit.successTitle': 'タネが蒔かれました！',
    'submit.successDesc': 'あなたのアイデアが App Gardenium に登録されました。コミュニティのメンバーが反応をくれるのを待ちましょう。新しい応援やコメントがあれば通知されます。',
    'submit.successExplore': '他のアイデアを探す',
    'submit.successProfile': 'マイページを見る',
    'submit.enhancing': '整えています...',
    'submit.enhance': 'AIに整理してもらう',
    'submit.enhanceHint': '1〜2項目だけでもOK。まだぼんやりでも、AIが言葉を整えるのを手伝います',
    'submit.aiLimitReached': '今日のβ版AI補助の上限に達しました。明日また試してみてください。',
    'submit.nameLabel': 'アイデア名',
    'submit.namePlaceholder': '例：雨の日だけ出る読書カフェマップ',
    'submit.summaryLabel': 'ひとことで言うと',
    'submit.summaryPlaceholder': '例：買う前に雰囲気を楽しめる、仮想アクセサリーショップ',
    'submit.audienceLabel': 'だれ向け？',
    'submit.audiencePlaceholder': '例：忙しいけど少し夢を見たい人',
    'submit.moreDetails': 'もっと詳しく書く（任意）',
    'submit.problemLabel': 'どんな課題？',
    'submit.problemPlaceholder': '具体的にどんなことに困っていますか？',
    'submit.alternativesLabel': '今はどうしてる？',
    'submit.alternativesPlaceholder': '現在はどうやって解決していますか？',
    'submit.frustrationsLabel': '何が物足りない？',
    'submit.frustrationsPlaceholder': '今の方法のどこが不満ですか？',
    'submit.minFeaturesLabel': '最初にほしい機能',
    'submit.minFeaturesPlaceholder': '最低限、どんな機能があれば試せそうですか？',
    'submit.tagsLabel': 'タグ（あとでもOK）',
    'submit.tagsPlaceholder': '例：読書, カフェ, コミュニティ',
    
    'common.back': '戻る',
    'common.allGrowthRecords': 'すべての成長記録を見に行く',
    'common.linkCopied': 'リンクをコピーしました！',
    'common.loading': '読み込み中...',
    'common.ideaNotFound': 'アイデアが見つかりません',
    'common.searchNoResults': 'アイデアが見つかりません',
    'common.searchNoResultsDesc': '条件に一致するアイデアは見つかりませんでした。',
    'common.clearFilters': 'フィルターを解除',
    'common.loginToPost': 'ログインして投稿する',
    // Mode Selection
    'submit.mode.title': '何を植えますか？',
    'submit.mode.seed': 'タネを置く',
    'submit.mode.seedDesc': '「あったらいいな」という願いや困りごとを置いてみよう。みんなの視点を足して育てていきます。',
    'submit.mode.sapling': '作りかけを持ち込む',
    'submit.mode.saplingDesc': '作りかけのプロトタイプや開発中のアプリを見せて、リアルな反応やテスターを集めましょう。',
    
    // Sapling Form
    'submit.sapling.title': '作りかけを持ち込む',
    'submit.sapling.subtitle': 'まだ途中でも、完成していなくても大丈夫。いまある形を見せることで、次にやるべきことが見えてきます。',
    'submit.sapling.nameLabel': 'アプリ・プロトタイプ名',
    'submit.sapling.summaryLabel': 'ひとことで言うと',
    'submit.sapling.whatItDoesLabel': '何ができる？',
    'submit.sapling.whatItDoesPlaceholder': '例：買い物リストを売り場順に自動で並べ替えられます。主な機能や使い方を簡潔に。',
    'submit.sapling.audienceLabel': 'だれ向け？',
    'submit.sapling.statusLabel': 'いまの進捗段階',
    'submit.sapling.statusMock': 'モック・デザインのみ',
    'submit.sapling.statusProto': 'プロトタイプあり',
    'submit.sapling.statusMvp': '最小限の機能あり',
    'submit.sapling.statusTesting': 'テスト中・改善中',
    'submit.sapling.lookLabel': 'いま見てほしいこと（複数可）',
    'submit.sapling.lookDirection': '方向性・コンセプト',
    'submit.sapling.lookUsability': '使いやすさ・UI',
    'submit.sapling.lookDesign': 'デザインの雰囲気',
    'submit.sapling.lookNeeds': '求められそうな機能',
    'submit.sapling.lookTesters': 'テスター募集',
    'submit.sapling.urlLabel': '試せるURL（任意）',
    'submit.sapling.urlHint': 'デモサイト、プロトタイプ、配布ページなどがあれば貼ってください。',
    'submit.demoUrlLabel': '試せるURL（任意）',
    'submit.demoUrlPlaceholder': 'https://...',
    'submit.sapling.screenshotsLabel': 'スクリーンショット（任意）',
    'submit.sapling.screenshotsHint': '1〜3枚。実際のUIを見せると反応がもらいやすくなります。',
    'submit.sapling.screenshotsNotice': '画像アップロードは準備中です。まずはURLのみでも投稿できます！',
    'submit.sapling.strugglesLabel': 'いま悩んでいること・ほしい反応（任意）',
    'submit.sapling.strugglesPlaceholder': '例：この操作が分かりにくいかも / デザインの雰囲気が合っているか見てほしい',
    'submit.sapling.submitBtn': 'この作りかけを置く',

    'idea.saplingBadge': '作りかけのアプリ',
    'idea.tryPrototype': 'プロトタイプを触ってみる',
    'idea.whatItDoes': '何ができる？',
    'idea.currentStatus': '開発ステータス',
    'idea.lookingFor': 'こんなフィードバックを求めています：',
    'idea.struggles': '現在の悩み・相談ごと',
    'idea.viewApp': 'アプリを見に行く',
    'idea.hasBoreFruit': 'このアイデア、実りました！',
    'idea.originSeed': 'この種から育ちました',
    'idea.originSapling': 'この苗が公開されました',
    'idea.grownFrom': 'みんなの応援を受けて、ついに実際のアプリとして公開されました。',
    'idea.growthLog': '成長の記録',
    'idea.atSeed': 'タネが置かれた',
    'idea.atSeedDesc': '最初の一歩。アイデアがこの場に蒔かれました。',
    'idea.atSapling': '苗として成長開始',
    'idea.atSaplingDesc': '開発が始まり、触れる形になりました。',
    'idea.atGrowing': 'みんなで育成',
    'idea.atTesting': 'テスト・改善',
    'idea.atTestingDesc': 'テスター募集と改善を繰り返し、磨きをかけてきました。',
    'idea.atReleased': '結実：アプリ公開',
    'idea.atReleasedDesc': 'App Gardenium から実際にアプリがリリースされました！',
    'home.shippedTitle': '最近実ったアプリ',
    'home.shippedDesc': 'App Gardenium から実際に生まれたアプリたちです。',
    'footer.tagline1': 'ひとり開発の芽を育てる場所。',
    'footer.tagline2': '小さく始めて、みんなで育てる。',
    'footer.support': 'サポート',
    'footer.terms': '利用規約',
    'footer.privacy': 'プライバシーポリシー',
    'footer.commerce': '特定商取引法に基づく表記',
    'footer.contact': 'お問い合わせ',
    'footer.creator': '制作',
    'footer.builtBy': '{name} によって制作されました。',
    'footer.betaNotice': 'App Gardenium は現在β版です。不具合や仕様変更が起こる可能性がありますが、いただいた声をもとに少しずつ整えていきます。',
    'tester.recruitTitle': 'テスターを募集する',
    'tester.recruitSubtitle': 'プロトタイプを実際のユーザーに触ってもらいませんか？伝わりやすいテスター募集文を作成しましょう。',
    'tester.backToProfile': 'マイページへ戻る',
    'tester.step1.title': 'どのアイデアで募集しますか？',
    'tester.step1.select': 'アイデアを選択...',
    'tester.step1.stageLabel': 'プロトタイプの段階を選んでください',
    'tester.stage.mockup': 'クリックできるモックアップ',
    'tester.stage.mockupDesc': 'Figma、Protopie など',
    'tester.stage.alpha': 'アルファ版',
    'tester.stage.alphaDesc': '粗いけれど動く状態',
    'tester.stage.beta': 'クローズドβ',
    'tester.stage.betaDesc': '公開前の仕上げ段階',
    'tester.nextStep': '次へ',
    'tester.step2.whoLabel': 'どんなテスターを募集しますか？',
    'tester.step2.whoHint': '具体的に！（例：「Macを使っているフリーランスデザイナー」「毎日散歩する犬の飼い主」など）',
    'tester.step2.whoPlaceholder': 'ターゲット層のプロフィール...',
    'tester.step2.whatLabel': '具体的に何をテストしたいですか？',
    'tester.step2.whatHint': '使いやすさ？価格設定？特定の機能が意味をなしているか？など',
    'tester.step2.whatPlaceholder': '例：オンボーディングの流れが分かりにくくないか知りたい。ガイドを見ずに新しいプロジェクトを作成できるか試してほしい。',
    'tester.step2.linkLabel': 'アクションリンク（任意）',
    'tester.step2.linkPlaceholder': 'figma.com/file/...',
    'tester.back': '戻る',
    'tester.postBtn': '募集を投稿する',
    'tester.submitting': '投稿中...',
    'tester.loadingIdeas': 'あなたのアイデアを読み込んでいます...',
    'tester.noIdeas': '先にアプリのアイデアを投稿すると、ここからテスター募集を出せます。',
    'tester.fetchError': 'アイデアを読み込めませんでした。再読み込みしてもう一度お試しください。',
    'tester.postError': 'テスター募集を投稿できませんでした。対象のアイデアを確認してもう一度お試しください。',
    'moderation.report': '通報',
    'moderation.reportPrompt': '確認してほしい内容を入力してください。任意ですが、詳細があると助かります。',
    'moderation.reportSent': '通報済み',
    'moderation.confirmDelete': 'このコンテンツを完全に削除しますか？',
    'admin.title': '管理: モデレーション',
    'admin.desc': 'ユーザー通報の確認、有害な公開投稿の非表示、ブースト申請の管理を行います。',
    'admin.forbiddenTitle': '管理者権限が必要です',
    'admin.forbiddenDesc': 'このページは管理者のみ利用できます。',
    'admin.reportsTitle': 'ユーザー通報',
    'admin.noReports': '現在対応待ちの通報はありません。',
    'admin.noDetails': '追加の詳細はありません。',
    'admin.hide': '非表示',
    'admin.delete': '削除',
    'admin.dismiss': '対応不要',
    'admin.boostsTitle': 'ブースト申請',
    'admin.noBoosts': '現在承認待ちのブースト申請はありません。',
    'admin.approve': '承認',
    'admin.reject': '却下',
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  toggleLanguage: () => {},
  t: (key: string) => key,
});

export const useLanguage = () => useContext(LanguageContext);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const setAppLanguage = (nextLang: Language) => {
    setLanguage(nextLang);
    localStorage.setItem('app_gardenium_lang', nextLang);
  };

  // Load language preference from localStorage on mount
  useEffect(() => {
    const pathLang = window.location.pathname.split('/').filter(Boolean)[0] as Language;
    if (pathLang === 'en' || pathLang === 'ja') {
      setAppLanguage(pathLang);
      return;
    }

    const savedLang = localStorage.getItem('app_gardenium_lang') as Language;
    if (savedLang === 'en' || savedLang === 'ja') {
      setLanguage(savedLang);
    } else {
      // Auto-detect based on browser
      if (navigator.language.startsWith('ja')) {
        setLanguage('ja');
      }
    }
  }, []);

  const toggleLanguage = () => {
    const nextLang = language === 'en' ? 'ja' : 'en';
    setAppLanguage(nextLang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: setAppLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}
